### ISSUE TITLE
Support for litterbox?

### ISSUE THREAD

**Issue by korewatori** [EnArvy/Catboxer#2]
I was wondering if you could add support for https://litterbox.catbox.moe as well, though I've been thinking about editing the code and adding it myself but I wasn't sure if you were already going to do it.

**Comment by EnArvy** [comment]
I decided to make another repository for that instead. Here is the link: https://github.com/EnArvy/Litterboxer
You are free to fork and include litterbox capability in this repo itself if you wish.
